// chapter-08/using-web-components-in-angular-and-vuejs/angular/my-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  myTitle = 'project-angular';
  open = false;
  title = 'app';

  toggle(event) {
    console.log(event);
    this.open = event.detail;
  }
}

<h1>Angular Application using Web Components</h1>

<p>
  {{ open ? 'open' : 'closed' }}
</p>

<x-dropdown [title]="myTitle" (show)="toggle($event)">
  Hello from Web Component in Angular!
</x-dropdown>

// chapter-09/using-web-components-in-react/my-app/src/App.js
import React, { Component } from 'react';
import Dropdown from './Dropdown';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      show: false,
      title: 'project-react'
    };
    this.handleShow = this.handleShow.bind(this);
  }

  render() {
    return (
      <div className="App">
        <h1>React Application Using Web Components</h1>
        <p>{this.state.show ? 'open' : 'closed'}</p>
        <Dropdown title={this.state.title} onShow={this.handleShow}>
          Hello from dropdown
        </Dropdown>
      </div>
    );
  }
  handleShow(e) {
    this.setState({ show: e.detail });
  }
}

export default App;
